name: make build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  make-build:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Make build
        shell: bash
        run: virtualenv venv && source venv/bin/activate && make install && make build
